# Give a short look to the whole file and you will already notice a confusing structure.
#  In first place, keys are not properly organized...
name: AwfulPlugin
commands:
 setblock:
  description: Setblock command. # Describe what the command does. We already know that setblock is a command.
  # Wondering where did the default key went through. (default is true)
  #  See this link for all possible default command permission values:
  #  https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/permission/Permission.php#L35-L38
  usage: "/setblock <x> <y> <z> <level> <block_id>"
  
# Useless keys that are not needed. By default, these are already empty ([])
permissions: []
depend: []
softdepend: []

description: A PocketMine plugin showing off bad coding practices (but it works!)

author: kenygamer
website: https://github.com/kenygamer

# A too generic namespace is being used here.
# Credit to SOFe who where the first in correcting me on this :P
main: plugin\Main
