# Confusing plugin.yml structure
name: AwfulPlugin
commands:
 setblock:
  description: Setblock command.
  # Wondering where did the default key went through.
  usage: "/setblock <x> <y> <z> <level> <block_id>"
  
# Useless config keys that are not needed
permissions: []
depend: []
softdepend: []

description: A PocketMine plugin showing off bad coding practices (but it works!)

author: kenygamer
# What is all this spacing for?
website: https://github.com/kenygamer

# Too generic namespaces
main: plugin\Main
